### ISSUE TITLE
클래스는 각기 고유의 package  에 작성해야 합니다

### ISSUE THREAD

**Issue by callor** [neck091/Biz-2023-11-505-java#1]
![image](https://github.com/neck091/Biz-2023-11-505-java/assets/23270330/ca665b67-746e-4c87-99fa-1b7eaabde380)

위 그림을 보면, 모든 패키지가 com.callor.scores 패키지에 있는데
utils, service 패키지를 분리하여 작성하세요

**Comment by neck091** [comment]
![image](https://github.com/neck091/Biz-2023-11-505-java/assets/151486054/7b7dbeec-3ec4-41d3-bc1a-2bf68832ddf0)

분리했습니다/
