### ISSUE TITLE
클래스 이름이 명확하지 않아요

### ISSUE THREAD

**Issue by callor** [neck091/Biz-2023-11-505-java#2]
![image](https://github.com/neck091/Biz-2023-11-505-java/assets/23270330/876a1c1f-fa9c-43d7-b85c-3ec5c7c76118)

클래스의 이름이 Stu 로 되어 있는데, 무엇을 하는 클래스인지 명확히 표현을 해야 합니다

코드 들여쓰기가 이클립스에는 제대로 보이나요?

**Comment by neck091** [comment]
![image](https://github.com/neck091/Biz-2023-11-505-java/assets/151486054/4d9928a2-e17e-4d36-92cf-e962fec0c962)

이름 변경. 들여쓰기같은 경우엔 전부 ctrl+shift+f 로 정리를 해둔 상태입니다.
