### ISSUE TITLE
scores 리스트의 선언과 생성(초기화)를 분리해야 합니다

### ISSUE THREAD

**Issue by callor** [neck091/Biz-2023-11-505-java#3]
![image](https://github.com/neck091/Biz-2023-11-505-java/assets/23270330/c5164b71-f333-49d1-b40d-fb5ba0b91c5d)

List<ScoreDto> scores 객체는 클래스 영역에서 생성하고 생성자에서 초기화를 해야 합니다

**Comment by neck091** [comment]
![image](https://github.com/neck091/Biz-2023-11-505-java/assets/151486054/9b8d2813-7bb8-48f4-a9c4-17a9fc4d46e8)

분리해서 수정완료했습니다
