### ISSUE TITLE
10명의 점수가 서로 다르게 생성되나요?

### ISSUE THREAD

**Issue by callor** [neck091/Biz-2023-11-505-java#4]
![image](https://github.com/neck091/Biz-2023-11-505-java/assets/23270330/e10a926e-bca0-4875-a89d-3fae4bac9753)

**Comment by neck091** [comment]
![image](https://github.com/neck091/Biz-2023-11-505-java/assets/151486054/37632581-694d-403f-80df-861d783cd2bc)

다르게 생성됩니다.

**Comment by callor** [comment]
한개의 변수값을 반복하여 재 생성하고 있습니다.
여기에서 반복문이 필요한 이유가 뭘까요

**Comment by neck091** [comment]
![image](https://github.com/neck091/Biz-2023-11-505-java/assets/151486054/3501da76-e577-48f9-8db2-745f9c795e3f)

for문 빼서 수정완료했습니다
