### ISSUE TITLE
전체평균을 이렇게 한 이유가 뭘까요

### ISSUE THREAD

**Issue by callor** [neck091/Biz-2023-11-505-java#5]
![image](https://github.com/neck091/Biz-2023-11-505-java/assets/23270330/eccc296d-5136-41b6-80b0-3e0a92cf5ee6)

**Comment by neck091** [comment]
![스크린샷 2023-12-08 142012](https://github.com/neck091/Biz-2023-11-505-java/assets/151486054/4619129a-485d-4ce2-bd06-807eec805495)

변수 추가,  전체평균 식 수정했습니다
