### ISSUE TITLE
main() 에서는 inputScore()를 한번만 호출해야 합니다

### ISSUE THREAD

**Issue by callor** [neck091/Biz-2023-11-505-java#6]
![image](https://github.com/neck091/Biz-2023-11-505-java/assets/23270330/5a06dc8a-bb6a-4c70-a061-1e5f97cb86e3)

main() 에서는 inputScore 를 한번만 호출하고
inputScore() 에서 10명의 학생 성적을 생성해야 합니다

**Comment by neck091** [comment]
![스크린샷 2023-12-08 141737](https://github.com/neck091/Biz-2023-11-505-java/assets/151486054/1e83276b-82bb-4e40-b55a-f0186bb6fdb5)

수정완료했습니다

**Comment by callor** [comment]
수고했습니다
